import json
import re

with open('data.js', 'r', encoding='utf-8') as f:
    content = f.read()

json_str = content.replace('const componentesData = ', '').strip()
if json_str.endswith(';'):
    json_str = json_str[:-1]

data = json.loads(json_str)

nuevas_caracteristicas = {
    "Termopar": "- Voltaje de Salida: Milivoltios (aprox 40 µV/°C Tipo K)\n- Rango Operativo: -270°C a +1370°C (Tipo K)\n- Interfaz: Analógica. Requiere chip amplificador (ej. MAX6675)\n- Linealidad: No lineal, requiere compensación digital.",
    "RTD (PT100, PT1000)": "- Tolerancia/Precisión: Clase A (±0.15°C)\n- Rango Operativo: -200°C a +850°C\n- Corriente de Excitación: < 1mA (para evitar auto-calentamiento)\n- Resistencia Nominal: 100Ω o 1000Ω a 0°C.",
    "Termistor (NTC, PTC)": "- Coeficiente Beta (B): Típicamente 3950K (NTC)\n- Rango Operativo: -55°C a +200°C\n- Resistencia Base (R25): 10kΩ a 100kΩ a 25°C\n- Interfaz: Transductivo (Se suele usar puente divisor de tensión).",
    "Sensor digital (DS18B20)": "- Voltaje Operativo: 3.0V a 5.5V\n- Interfaz de Datos: Protocolo 1-Wire (un solo pin de datos)\n- Resolución ADC: 9 a 12 bits seleccionable (0.5°C a 0.0625°C)\n- Consumo Máx: 1.5mA (activo) / 1000 nA (standby).",
    "Capacitivo / Resistivo": "- Frecuencia de Excitación: Varía entre 1kHz a 100kHz\n- Tiempo de respuesta: aprox. 5 a 10 segundos.\n- Deriva anual: < 1% HR/año\n- Rango HR: 0 a 100% Humedad Relativa.",
    "Módulo DHT11/DHT22": "- Operación DHT22: 3.3V-5.5V\n- Rango Temp/Hum (DHT22): -40 a 80°C (±0.5°C) / 0 a 100% HR (±2%)\n- Tasa Muestreo: 0.5Hz (Una vez cada 2 segundos)\n- Interfaz: Bus digital serial (protocolo propio).",
    "Piezorresistivos / Capacitivos": "- Rango de Presión Absoluta: 300 hPa a 1100 hPa (ej. BMP280)\n- Resolución RMS: 0.01 hPa (BMP280)\n- Interfaz de comunicación: I2C o SPI\n- Corriente Standby: 0.1 µA.",
    "Inductivo / Capacitivo": "- Frecuencia de Conmutación: hasta 2 kHz (Inductivos)\n- Distancia Sensado: 1 mm a 50 mm dependiente de masa\n- Salida Lógica: NPN o PNP (Normalmente Abierto o Cerrado)\n- Voltaje Industrial: Típico 12V a 24V DC.",
    "Ultrasónico (HC-SR04)": "- Frecuencia Ultrasonido: 40 kHz\n- Rango Efectivo: 2 cm a 400 cm\n- Resolución: 0.3 cm\n- Ángulo de apertura de propagación: < 15 grados.",
    "Infrarrojo (PIR)": "- Consumo: ~65mA\n- Distancia o Rango Detección: Ajustable físicamente de 3m a 7m\n- Ángulo Cono Detección: 110 a 120 grados\n- Temporizador: Pulso ajustable de 0.3s a 5min.",
    "Fotorresistencia (LDR)": "- Resistencia (Oscuridad): ~1 MΩ a 10 MΩ\n- Resistencia (Luz / 10 Lux): ~10 kΩ a 20 kΩ\n- Longitud Límite Resonante: Sensibilidad máxima en ~540 nm (verde/amarillo)\n- Tiempo de Reacción: 20 ms a 30 ms.",
    "Fotodiodo / Fototransistor": "- Corriente Oscuridad (Típica): 1 nA a 50 nA\n- Tiempos de Ascenso/Caída (Tr/Tf): < 5 ns (Fotodiodo) / 5 µs (Fototransistor)\n- Longitud de Onda Sensitiva: 400 nm a 1100 nm (máx en ~900 nm para IR)\n- Ganancia: el Fototransistor hFE > 100 respecto al fotodiodo.",
    "Sensor de color": "- Distribución de filtro: RGB + Clear (Chips tipo TCS34725)\n- Integración ADC: Salida I2C con conversores 16-bits por canal\n- Rango Dinámico Lumínico: ~3.800.000:1\n- Distancia de lectura: Preferiblemente a ~1 cm de reflexión.",
    "Encoder Incremental / Absoluto": "- Resolución Incremental (PPR): Usualmente 20 a 10,000 Pulsos Por Vuelta\n- Voltaje: 5V a 24V (Salida Push-Pull / Open Collector)\n- Protocolo Absoluto: SSI, BiSS u OCR Binario de Grey paralelo\n- Tolerancia a la Revolución: Hasta 6000 RPM (mecánico).",
    "Motor con escobillas": "- Voltaje Típico: 1.5V a 24V DC\n- RPM Típica: 100 (juguetes) hasta 20,000 (drones base)\n- Torque Típico: Muy dinámico (relacionado matemáticamente a Corriente)\n- Controles: Voltaje directo o Puente H (PWM).",
    "Motor sin escobillas (BLDC)": "- Kv (RPM por Voltio): 100Kv a 5000Kv\n- Fases: 3 Cables (U, V, W)\n- Eficiencia Eléctrica: 85% a 90% (vs 70% de DC tradicionales)\n- Corrientes de pico altas: 20A a +150A con Drivers Trifásicos (ESC).",
    "Servomotor": "- Frecuencia de PWM de Control: 50 Hz (Ventana 20ms)\n- Duty Cycle de giro: 1 ms (A 0°) a 2 ms (A 180°)\n- Torque Holding (Stall Torque): ~10 kg-cm a 5V (modelos comunes MG996R)\n- Deadband: ~1-5 microsegundos de tolerancia.",
    "Motor paso a paso": "- Ángulo por Paso: Típicamente 1.8° (200 pasos/rev) o 0.9°\n- Fases Físicas: 2 (Bipolar) o 4 (Unipolar)\n- Par de Mantenimiento (Holding Torque): Ej. 0.4 Nm (NEMA 17 básico)\n- Voltaje e Intensidad Nominal: Suele requerir control de corriente constante.",
    "Solenoide Lineal/Rotatorio": "- Voltaje de Tensión: 5V, 12V o 24V DC\n- Carrera del resorte (Stroke): 5 mm a 30 mm\n- Fuerza Máx. de Tracción: 10N a +500N dependiendo del chasis\n- Duty Cycle Crítico: Suele requerir descansos o disipadores de calor (baja impedancia).",
    "Relé Electromecánico": "- Circuito de Control (Bobina): 5V, 12V, 24V DC (~50 a 100 mA)\n- Tolerancia Capacidad Conmutación: 10A / 250V AC, 10A / 30V DC\n- Arqueo Mecánico: Sensible a desgasificación e inductancias reactivas\n- Tiempo Conmutación (ms): ~5 a 15 ms mecánicos.",
    "Relé de estado sólido (SSR)": "- Aislamiento Óptico Galvánico: Usualmente mayor a 4000Vrms\n- Rango Conmutación Salida: 24 a 380 VAC @ 40A (Triac) / DC SSR usan MOSFETs\n- Tiempo Reacción conmutación zero: Máximo ciclo medio de red (8ms en 60Hz)\n- Tensión Control Interna: 3 a 32V DC.",
    "Electroválvula (Solenoide)": "- Modo Operativo: Normal Abierta (NO) / Normal Cerrada (NC) (Bidireccional)\n- Presión Flujo: 0.02 a 0.8 MPa (Depende del diafragma piloto)\n- Rosca Pipa Típica: 1/2\" o 3/4\" NPT\n- Fluidos Compatibles: Agua dulce, gases (dependiendo de la empaquetadura material).",
    "Actuador Piezoeléctrico": "- Voltaje Operacional: Muy elevados, comúnmente 100V a 1000V en nanosegundos.\n- Resolución Excursión: Sub-nanómetros hasta milímetros (Multilayer).\n- Frecuencia Resonancia Tracción: >100 kHz.\n- Bloqueo de Fuerza Máx: Decenas de kiloNewtons en apilados cerámicos gruesos.",
    "Arduino (ATmega328P)": "- CPU Architecture: AVR 8-bit RISC a 16 MHz.\n- Memoria Flash (Program Space): 32 KB.\n- Memoria SRAM: 2 KB.\n- I/O Periféricos: 20 IO Totales (6 PWM Hard. y 6 ADC Multipl.)\n- Rango Operación Fuerte: 5V lógico (soporta entrada desde 7-12V directo).",
    "ESP32 / ESP8266": "- Microprocesador MIPS: Xtensa Dual-Core 32-bit LX6 @ 160 o 240 MHz.\n- Interfaz Inalámbrica RF: Wi-Fi 802.11 b/g/n / Bluetooth Clásico & BLE v4.2.\n- ROM/SRAM Externa: Flash SPI típicamente 4MB - RAM Int. 520 KB.\n- Tensión Circuito: Lógica ultra críctica 3.3V (no tolera 5V por defecto).",
    "STM32": "- Arquitectura Interna Escalar: ARM Cortex-M0/M3/M4/M7 dependiente de línea.\n- Frecuencia Reloj: de 48 MHz (serie F0) a ~400+ MHz (serie H7).\n- Sub-interfaces HW Dedicados: CAN Bus embebido interno, SDIO Flash, I2S DAC Audio.\n- Conversión: Canales ADC con resolución de 12 a 16-bits ultrarrápidos (Msps).",
    "PLC Compacto / Modular": "- Procesamiento de Ciclo (Scan Time): usualmente bajo 1ms por cada 1K de código.\n- Hardware Entradas: Aisladas galvánicamente (24VDC sumidero/fuente) e Inmunidad Ruido IEC 61131-2.\n- Lenguajes Normativos: Ladder (LD), Estructurado (ST), Función Bloque (FBD).\n- Expansibilidad E/S: Módulos rack para termocuplas, salidas a red industrial (PROFINET).",
    "Raspberry Pi": "- CPU Complex Unit: Cortex A72 (Pi4) Quad core a 1.5+ GHz.\n- RAM: 1GB a 8GB LPDDR4 compartida para VRAM GPU.\n- Sistema E/S PinHeader: 40 pines directos al BCM SOC 3.3V, I2C dual, SPI, Serial UART.\n- Interfaces Video/Lan: HDMI, MIPI CSI/DSI directo al silicio, PHY Ethernet Gigabit.",
    "Jetson Nano / BeagleBone": "- (BeagleBone) Sitara AM335x: Integra PRUs (Programmable Realtime Units) que evitan kernel interruptions.\n- (Jetson Nano): GPU NVIDIA Maxwell con 128 CUDA Cores, logrando 472 GFLOPs AI FP16.\n- E/S MIPI Lense: Hasta puertos cuádruples Mipi por hardware para estéreo fotogrametría HD.\n- Arquitectura del CPU: Quad ARM Cortex A57 64-bit.",
    "Drivers DC / Paso a paso": "- Rango de Potencia/Voltaje: 5V hasta 35V+.\n- Máxima Corriente Directa soportada: Chips L298 (~2A puente), A4988 (~2A pico microstep).\n- Control PWM/StepL: Subdivisión de pulsos para mayor Torque/Suavidad de fase (Microstepping 1/16 a 1/256 en Trinamic TLC).\n- Thermal Shutdown Limit: Apagado protector cerca de los 150°C.",
    "Módulo WiFi / Bluetooth": "- MAC Layer Protocol: Estandar IEEE 802.11 b/g/n y Protocolo BLE PHY/Layer GATT.\n- Voltaje UART Comm: 3.3V TTL (HC-05 requiere conversor nivel vs 5V del Arduino).\n- Sensibilidad RSSI Antena: Aproximado de -90 dBm con trazador planar de PCB integrado.\n- Tasa de Bits Nominal Perfil RF: Bluetooth SPP (~2 Mbps pico).",
    "LoRa / LoRaWAN": "- Ancho de Banda Programable Espectro: 125 kHz, 250 kHz o 500 kHz.\n- Propagación Factores Ruido (SF): SF7 a SF12 (SF mayor denota más rango con bitrate más lento).\n- Presupuesto de Enlace Logístico (Link Budget): 157 dB +14 dBm (alcances > 15 Kilómetros en LOS).\n- Frecuencia regional Banda ISM permitida: Ej. EU 868MHz, US 915MHz.",
    "Zigbee": "- Transmisión PHY/MAC Base RF: IEEE 802.15.4 a banda mundial 2.4 GHz ISM.\n- Nodo Co-operativo Coordinador/Router/Dispositivo Final: Arquitectura multi-rol Mesh Tolerante Falla.\n- Cifrado Red Abstracción: Seguridad AES-128 con Trust Center Link Keys intracadena.\n- Corriente Ultra Baja (Sleep final node): ~1 microamperio standby de años de autonomía.",
    "RS-232 / RS-485": "- Niveles Señal (RS-232): Cargas Unipolares Pos/Neg de -15V a +15V.\n- Inmunidad Ruido (RS-485): Diferencial balanceada (Terminales +/-A y B diferencial).\n- Distancia Limitante en Cobre: RS-232 (~15m a 19kbps), RS-485 (~1200m en Twisted Pair AWG).\n- Topología Serial: RS-485 es Multiterminal Multipunto (Hasta 32 dispositivos en bus half-duplex).",
    "CAN Bus / Ethernet": "- Ratio Tranferencia (CAN): 1 Mbaud máximo tolerando distancias ~40 m.\n- Arquitectura Trama Control: CAN (11 o 29 Bits Extended) Carrier Sense Multiple Access c/ Arbitration por prioridad Mensaje.\n- Inmunidad a Fallos EMI de Vehículos: Alta, trenzs de cables diferencias aisladas.\n- Ethernet PHY Automotriz: Capa base T1 trans-diferencial.",
    "Rector RFID / NFC": "- Frecuencia de Activación Operativa: ~125 kHz (LF RFID Antiguo) y 13.56 MHz (NFC y RFID HF).\n- Protocolo Seguridad HF/NFC: ISO/IEC 14443 (MIFARE).\n- Rango Antena a Chip pasivo: Contacto leve hasta ~10 cm máximo para NF.\n- Formatos Payload Data NFC: Formato Estándar NDFF.",
    "Módulo SIM800L / SIM900": "- Modulación Radio Celular Red Telco: Cuatribanda 850/900/1800/1900 MHz (Red 2G legada).\n- Interfaz Control Hardware Firmware: Comandos AT Estándares (Ej: AT+CMGF para SMS o GPRS CREG).\n- Tensión Operacional Sensible: Obligatoriamente centrado en 3.7 V – 4.2 V.\n- Picos de Encendido TX: Tira hasta 2 Amperios de golpe por milisegundos buscando repetidoras.",
    "BJT (NPN, PNP)": "- Ganancia de Corriente del Transistor DC (h_FE / Beta): Normalmente de ~100 a ~300 en saturación media (como 2N2222).\n- Voltaje Colecctor-Emisor (V_CEO Max): +40 V (Típicos de Switch P. ej. 2N2222A/3904).\n- Frecuencia Límite Ganancia(f_T): Hasta ráfagas 300 Mhz ancho de banda conmutador.\n- Consumo Límite Corriente (I_C): ~200 mA a 800 mA de tope seguro.",
    "MOSFET / IGBT": "- Tensión Puerta Umbral Trigger (V_GS (th)): Puede operar desde 1.5V (Logic Levels) o exigir sobre 10V (Power MOSFETs de RdsOn bajos).\n- Resistencia Encendida Dinámica R_DS(on): UltraBaja (A veces menos de 5 mΩ = mínimos disipadores.\n- Tolerancia Drain a Source Voltaje y Amperaje: De ~60 V @ 30A genéricos hasta mosfets de tramos +800V.\n- Capacidad Parásita Gate a Source: ~1 a 4 nF (requiere drivers de compuerta activos).",
    "Amplificador Operacional": "- Alta Tensión Rechazo Modo Común (CMRR): Suele estar encima de 90 dB.\n- Ganancia Lazo Abierto Natural: > 100,000 en baja frecuencia (DC).\n- Limitación Velocidad Respuesta Máx (Slew Rate): De ~0.5 V/µs (Ua741) hasta > 5000 V/µs en Fast-OpAmps alta fidelidad.\n- Impedancia Terminal (+) Entrada: Infinita en FETS (>10 TeraOhmios) impidiendo extraer corriente al sensor.",
    "Regulador de voltaje": "- Drop Out Voltage Disipativo Diferencial: Para serie L78XX mínimo necesita ~2V Arriba del límite final de salida deseable.\n- Disipación de Carga Térmica Natural: PD = (Vin - Vout) * I. Se hornean sin Radiadores o disipadores grandes en metales.\n- Protección Cierre Interno (Foldback): Corte automático general térmico aproximado a los ~125 °C internos.\n- LDOs y SMPS: Tipos LM2596 (Switching) alcanzan el ~90% de eficiencia evitando disipar V*I, emitiendo inducción.",
    "Temporizador 555": "- Temporización Matemáticamente Cierta: Variable R/C simple de un condensador T = 1.1 * R * C (monoestable pulso retardado).\n- Margen Vcc Alimentación Flexible: 4.5V Típicamente a +15V para serie NE/CMOS.\n- Capacidad Corriente Pin Salida (Discharger/Output): Excepcional Drive Ditecto Sinc. hasta 200 mA para prender relés solo.\n- Operatividad Grados Celsius Límides: 0 ºC a +70 °C genéricos.",
    "LEDs / Displays": "- Forward Voltages Físicos Colorizados(V_F): Rojo~2V, Verde/Azul~3.2V, Infrarrojo (850nm)~1.5V.\n- Resiliencia a Inversiones (Reverse Breakdown Rígida): Destrucción frágil de unión a la reversión (-5 V DC).\n- Luminiscencia Potencia y Vida: Corrientes Directas Mínicas Estáticas (I_F) desde 10mA en THT (Agujero). Su decaimiento luminoso a 50k - 100k Horas.\n- Componente Matrix Display Multiplexado: Revierten duty cycles de parpadeos persistencia retina (Refresco +60Hz).",
    "Optoacoplador": "- Aislación Galvanoplástica Promedio Rango (V_iso): > 5000 Voltios RMS resinas plásticas dieléctricas separadoras.\n- Factor Transmisivo de Corriente Real (CTR ratio Ganancia): Entre 50% al 600%.\n- Frecuencia de Conmutación Luz Max: ~80 kHz para transistores comunes (PC817); mayores con Optos Lógicos digitales (6N137 High Speed Logic).\n- Umbral LEDs Emisores Int. Cobre: Requierne la misma ley un LED simple (ej: aprox ~10-20mA en ~1.2V In).",
    "Resistencia": "- Disipación Térmica en Vatios W: Clásicas (1/4 de Whatt o 0.25W), Cerámicas Cementadas (5W a +20 Watios).\n- Tolerancia Factor Error Manufacturacion: En Carbón 5% dorada fina; Metal Film 1% hasta 0.1% extremas de precisión fina analógica.\n- Tolerancia Coef. Temp Coef (TCR): Variabilidad al resistir (alambres se desplazan unos ~50ppm/°C).\n- Estándar Rango Físico Codificado Axial(SMD Equivalencias): SMD Tipo 0805 o Tipo 1206 en PCBs montables de escala.",
    "Capacitor": "- Rango de Valores Estáticos en Faradios Diélectricos Variados: PicoFaradios (pF) para Cerámicos filtrado ruido. Microfaradios (µF / +1mF) Electrolíticos buffer carga.\n- Voltage Rating Max AC/DC Cargas (V_Max): Rompimiento diélectricos; comúnmente x2 de la carga prevista en PCB (10v, 16V, 25v DC hasta 400vAC).\n- ESR Parásito (Equiv Serie Resist): Impide velocidades muy rápidas pulsos en capacitadores de mala clase Electrolíticos impuros (Mili-Ohmios).\n- Frecuencias Resonance R-L-C Natural: El capacitor puro es utopico; filtran solo cierto ancho de ruidos F.",
    "Inductor": "- Inductancias Valoraciones Unidades Magnitud Típica: Micro, Mili o Henrios (µH, mH, H).\n- Frecuencia Resonancia Saturamiento (SRF / Sat): Límite donde núcleo Hierro Polvos se satura y se cae impedancia (Inductores dejan pasar DC).\n- Composición Chocke Material/Núcleo Específico: Ferritas puras, Polvo de hierro aglutinado (Bajas perdidas de histéresis Alta frec.) Toroides.\n- Clasificaciones de Tolerancia de Corriente Efectiva y RMS Resistividad (DCR): Caliente, hasta derretimiento alambre barnizado (AWG diámetro milésimas)."
}

for item in data:
    nombre = item["nombre"]
    if nombre in nuevas_caracteristicas:
        item["caracteristicas"] = nuevas_caracteristicas[nombre]

with open('data.js', 'w', encoding='utf-8') as f:
    f.write('const componentesData = ' + json.dumps(data, indent=4, ensure_ascii=False) + ';')

print("Fueron actualizadas las características técnicas avanzadas de manera exitosa para profunda ingeniería.")
